max_seq_size: 512

d_hidden: 256 # paper에는 768
n_layers: 6  # paper에는 12 
n_heads: 12
n_outputs: 2
dropout_rate: 0.3

bos_token: "[BOS]"
eos_token: "[EOS]"
unk_token: "[UNK]"
pad_token: "[PAD]"
delim_token: "$"